import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#faf9fc",
        "surface-container-highest": "#e3e2e5",
        "primary-fixed": "#d1e4ff",
        "secondary-container": "#88f4f3",
        error: "#ba1a1a",
        outline: "#73777f",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#a8c9f3",
        "inverse-on-surface": "#f1f0f4",
        "surface-tint": "#3f6185",
        "surface-container-low": "#f4f3f6",
        "on-tertiary-container": "#f6765f",
        "tertiary-fixed-dim": "#ffb4a6",
        tertiary: "#450400",
        "primary-container": "#0f3658",
        "on-primary-fixed": "#001d35",
        "on-surface": "#1a1c1e",
        "on-primary-fixed-variant": "#26496c",
        "surface-container-high": "#e8e8eb",
        "surface-variant": "#e3e2e5",
        "on-tertiary-fixed": "#3f0300",
        "error-container": "#ffdad6",
        "inverse-surface": "#2f3033",
        "on-secondary-container": "#007070",
        "on-primary-container": "#7e9fc7",
        "inverse-primary": "#a8c9f3",
        surface: "#faf9fc",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed": "#002020",
        primary: "#00203b",
        "on-background": "#1a1c1e",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "outline-variant": "#c3c7cf",
        "surface-bright": "#faf9fc",
        "on-tertiary-fixed-variant": "#852314",
        "tertiary-container": "#6a0f03",
        "tertiary-fixed": "#ffdad3",
        "surface-container": "#eeedf1",
        "on-secondary": "#ffffff",
        "surface-dim": "#dadadd",
        "on-surface-variant": "#43474e",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#6bd7d7",
        "secondary-fixed": "#88f4f3",
        secondary: "#006a6a",
        "on-secondary-fixed-variant": "#004f50",
        "brand-cream": "#FEFEE8",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1280px",
        "margin-mobile": "24px",
        gutter: "32px",
        "stack-md": "24px",
        "stack-sm": "12px",
        "margin-desktop": "64px",
        "section-gap": "120px",
        unit: "8px",
        "stack-lg": "48px",
      },
      fontFamily: {
        "body-lg": ["Quicksand", "sans-serif"],
        "label-caps": ["Quicksand", "sans-serif"],
        "headline-lg": ["Quicksand", "sans-serif"],
        "display-lg": ["Quicksand", "sans-serif"],
        "display-lg-mobile": ["Quicksand", "sans-serif"],
        "headline-md": ["Quicksand", "sans-serif"],
        "body-md": ["Quicksand", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "500" }],
        "label-caps": [
          "12px",
          { lineHeight: "1.0", letterSpacing: "0.05em", fontWeight: "700" },
        ],
        "headline-lg": ["32px", { lineHeight: "1.3", fontWeight: "700" }],
        "display-lg": [
          "56px",
          { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "display-lg-mobile": ["40px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};

export default config;
